### PR TITLE
LPS-114416 Fix margin of the content body

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jacobcerda** [comment]
This build has failed due to Assertion and Null Pointer errors:
java.lang.NullPointerException
	at com.liferay.portal.service.permission.GroupPermissionImpl.contains(GroupPermissionImpl.java:96)
	at com.liferay.portal.service.permission.GroupPermissionImpl.contains(GroupPermissionImpl.java:118)
	at com.liferay.portal.service.permission.GroupPermissionImpl.check(GroupPermissionImpl.java:64)
	at com.liferay.portal.kernel.service.permission.GroupPermissionUtil.check(GroupPermissionUtil.java:37)
	at com.liferay.exportimport.internal.staging.StagingImpl._checkPermission(StagingImpl.java:3961)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2281)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2372)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2329)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2384)
	at com.liferay.exportimport.kernel.staging.StagingUtil.publishLayouts(StagingUtil.java:333)
	at com.liferay.portlet.exportimport.service.impl.StagingLocalServiceImpl.enableLocalStaging(StagingLocalServiceImpl.java:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMeth...
PortalLogAssertorTest.testScanXMLLog
junit.framework.AssertionFailedError: 
Unable to disable staging for group 46399
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)

**Comment by jacobcerda** [comment]
These are the Errors( [Full log ](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/400699/consoleText)): 
java.lang.NullPointerException
	at com.liferay.portal.service.permission.GroupPermissionImpl.contains(GroupPermissionImpl.java:96)
	at com.liferay.portal.service.permission.GroupPermissionImpl.contains(GroupPermissionImpl.java:118)
	at com.liferay.portal.service.permission.GroupPermissionImpl.check(GroupPermissionImpl.java:64)
	at com.liferay.portal.kernel.service.permission.GroupPermissionUtil.check(GroupPermissionUtil.java:37)
	at com.liferay.exportimport.internal.staging.StagingImpl._checkPermission(StagingImpl.java:3961)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2281)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2372)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2329)
	at com.liferay.exportimport.internal.staging.StagingImpl.publishLayouts(StagingImpl.java:2384)
	at com.liferay.exportimport.kernel.staging.StagingUtil.publishLayouts(StagingUtil.java:333)
	at com.liferay.portlet.exportimport.service.impl.StagingLocalServiceImpl.enableLocalStaging(StagingLocalServiceImpl.java:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMeth...

and

junit.framework.AssertionFailedError: 
    [junit] Unable to disable staging for group 41325
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
    [junit] 


These errors are probably occurring in upstream and are not unique to this PR.

**Pull request closed without merging**
