### PR TITLE
LPS-86606 Correction to fix failing tests on CI

### PR DESCRIPTION
**Pull request by renatodepaiva**

### CODE REVIEW

**Comment by renatodepaiva** [comment]
I executed some of the tests here: https://github.com/renatodepaiva/liferay-portal/pull/35

**Comment by marcelabc** [comment]
ci:help

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
LGTM

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65249. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
