### PR TITLE
LPS-91356 Send backURL to record_action

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69815. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
