### PR TITLE
LPS-93139 Rename

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/126. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/127. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/451. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
