### PR TITLE
LPS-91401 Add DataView delete feature

### PR DESCRIPTION
**Pull request by mclomello**
@marcelabc

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
@marcelabc Could you please run ci:test:sf and ci:test:relevant please? 

I already configured the CI but for some reason it still not working.

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
@mclomello There is an error involving data-engine-test, can you take a look at it?

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69471. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
