### PR TITLE
LPS-129892 Fix TextHTMLField syncReadOnlyUI method

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @marcelabc ,
Based on your [comment](https://github.com/liferay-data-engine/liferay-portal-ee/pull/17#issuecomment-820714810) I made the changes to master. 
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
I'm not sure this sf fail is related

**Comment by marcelabc** [comment]
Hi @MarcellGyopos ! 
Could you send this to the data engine repository ( liferay-data-engine/liferay-portal )? Thank you for the work! 😄

**Pull request closed without merging**
