### PR TITLE
LPS-103901 Replacing Text Field by Text at ViewDefaultFieldNamesWithPunctuationCharacters test case

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:test:forms

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:stop

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:test:forms

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/202. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/203. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/684. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
