### PR TITLE
LPS-98083 scope can be negative

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76719. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
