### PR TITLE
LPS-87625 Create DEDataLayout service

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/62. [See changes here.](https://github.com/marcelabc/liferay-portal/compare/520a4c19e6cb~2...520a4c19e6cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
