### PR TITLE
LPS-83895 fix unit tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielwas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Pull request submitted to https://github.com/marcelabc/liferay-portal/pull/15. [See changes here.](https://github.com/marcelabc/liferay-portal/compare/7d3f235eec55~2...7d3f235eec55) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
